export const SAMPLE_TEXTS = [
    'Das ist ein fantastischer Kurs!',
    'Heute scheint die Sonne sehr hell.',
    'Ich gehe morgen früh zum Bäcker.',
    'Der Hund spielt mit einem roten Ball.',
    'Wir treffen uns am Bahnhof um sieben Uhr.',
    'Das Wetter wird am Wochenende besser.',
    'Sie liest ein spannendes Buch im Garten.',
    'Mein Bruder studiert Informatik in Berlin.',
    'Die Katze schläft auf dem warmen Sofa.',
    'Wir kochen heute Abend Spaghetti Bolognese.',
    'Das neue Restaurant in der Stadt ist ausgezeichnet.',
    'Ich habe gestern einen interessanten Film gesehen.',
    'Die Kinder spielen im Park Fußball.',
    'Mein Auto ist leider in der Werkstatt.',
    'Der Lehrer erklärt die Aufgabe sehr deutlich.',
    'Wir fahren im Sommer ans Meer.',
    'Das Konzert war ein großer Erfolg.',
    'Sie kauft frisches Obst auf dem Markt.',
    'Mein Computer ist heute Morgen abgestürzt.',
    'Die Bibliothek schließt um acht Uhr abends.',
    'Wir feiern morgen den Geburtstag meiner Mutter.',
    'Der Zug kommt in zehn Minuten an.',
    'Ich trinke gerne Kaffee am Morgen.',
    'Das Museum bietet kostenlose Führungen an.',
    'Mein Nachbar hat einen sehr lauten Hund.',
    'Wir gehen am Samstag wandern.',
    'Die Kinder lernen schnell neue Sprachen.',
    'Sie arbeitet als Ärztin im Krankenhaus.',
    'Der Park ist heute besonders voll.',
    'Ich brauche dringend einen neuen Laptop.',
    'Das Essen im Hotel war hervorragend.',
    'Wir haben einen langen Spaziergang gemacht.',
    'Die Blumen im Garten blühen wunderschön.',
    'Mein Freund kommt nächste Woche zu Besuch.',
    'Der Verkehr ist heute besonders schlimm.',
    'Sie spielt sehr gut Klavier.',
    'Wir trinken zusammen ein Glas Wein.',
    'Das Flugzeug startet pünktlich um zehn.',
    'Ich habe meinen Schlüssel zu Hause vergessen.',
    'Die Universität bietet viele interessante Kurse an.',
    'Mein Kollege hilft mir bei dem Projekt.',
    'Wir fahren mit dem Fahrrad zur Arbeit.',
    'Das Wasser im See ist sehr kalt.',
    'Sie singt jeden Sonntag im Chor.',
    'Der Markt hat heute besonders frisches Gemüse.',
    'Ich lese gerade einen historischen Roman.',
    'Das neue Smartphone hat eine tolle Kamera.',
    'Wir bauen ein Baumhaus für die Kinder.',
    'Die Aussicht von dem Berg ist atemberaubend.',
    'Mein Onkel arbeitet als Pilot bei einer Fluggesellschaft.',
    'Wir essen heute Abend in einem italienischen Restaurant.',
    'Der kleine Junge lernt gerade Fahrrad fahren.',
    'Sie hat eine wunderschöne Stimme zum Singen.',
    'Das Hotel liegt direkt am Strand.',
    'Ich gehe jeden Morgen joggen im Park.',
    'Die Kinder freuen sich auf die Sommerferien.',
    'Mein Großvater erzählt gerne alte Geschichten.',
    'Wir haben einen neuen Welpen adoptiert.',
    'Das Theaterstück gestern war wirklich beeindruckend.',
    'Sie organisiert eine große Party für ihren Mann.',
    'Der Bus fährt alle zwanzig Minuten.',
    'Ich muss noch dringend einkaufen gehen.',
    'Die alte Brücke wird gerade renoviert.',
    'Mein Bruder hat einen neuen Job bekommen.',
    'Wir genießen den ruhigen Abend zu Hause.',
    'Das Restaurant serviert traditionelle bayerische Küche.',
    'Sie schreibt ein Buch über ihre Reisen.',
    'Der Garten braucht dringend neuen Dünger.',
    'Ich höre jeden Tag klassische Musik.',
    'Die Schule beginnt um acht Uhr morgens.',
    'Mein Vater repariert das kaputte Fahrrad.',
    'Wir planen einen Urlaub in den Bergen.',
    'Das Wetter ändert sich sehr schnell heute.',
    'Sie unterrichtet Mathematik an einer Grundschule.',
    'Der Künstler malt wunderschöne Landschaftsbilder.',
    'Ich brauche ein neues Paar Schuhe für den Winter.',
    'Die Bäckerei verkauft das beste Brot der Stadt.',
    'Mein Freund hat sich gestern den Arm gebrochen.',
    'Wir besuchen am Sonntag meine Großeltern.',
    'Das Kino zeigt heute Abend einen Klassiker.',
    'Sie tanzt seit ihrer Kindheit Ballett.',
    'Der Kuchen schmeckt absolut köstlich.',
    'Ich habe eine wichtige Besprechung am Nachmittag.',
    'Die Berge sind im Winter mit Schnee bedeckt.',
    'Mein Hund liebt es im Wald spazieren zu gehen.',
    'Wir treffen uns heute Abend in der Bar.',
    'Das Buch ist sehr spannend von Anfang bis Ende.',
    'Sie macht jeden Tag eine Stunde Yoga.',
    'Der Fluss ist nach dem Regen sehr breit geworden.',
    'Ich lerne gerade eine neue Programmiersprache.',
    'Die Stadt ist nachts wunderschön beleuchtet.',
    'Mein Sohn hat heute seinen ersten Schultag.',
    'Wir verreisen nächsten Monat nach Spanien.',
    'Das Konzert findet im großen Stadtpark statt.',
    'Sie kocht das beste Schnitzel der ganzen Familie.',
    'Der Zoo hat einen neuen Pandabären bekommen.',
    'Ich brauche eine kurze Pause vom Arbeiten.',
    'Die Bahnverbindung nach München ist sehr gut.',
    'Mein Cousin heiratet im nächsten Frühling.',
    'Wir putzen das ganze Haus am Wochenende.',
    'Das Internet ist heute besonders langsam.',
    'Sie sammelt seit Jahren alte Briefmarken.',
    'Der Markt findet jeden Mittwoch und Samstag statt.',
    'Ich vergesse oft meinen Regenschirm zu Hause.',
    'Die Bäume verlieren im Herbst ihre Blätter.',
    'Mein Chef ist heute sehr gut gelaunt.',
    'Wir machen einen Ausflug zum nahen Schloss.',
    'Das Fenster lässt sich nicht mehr richtig schließen.',
    'Sie übt jeden Abend zwei Stunden Geige.',
    'Der Sportverein sucht neue Mitglieder.',
    'Ich freue mich schon auf das Wochenende.',
    'Die Apotheke ist gleich um die Ecke.',
    'Mein Bruder zieht im Sommer nach Hamburg.',
    'Wir essen sonntags immer gemeinsam zu Mittag.',
    'Das Fußballspiel beginnt heute um halb neun.',
    'Sie besucht ihre Tante einmal im Monat.',
    'Der Wind weht heute besonders stark.',
    'Ich kaufe meiner Frau einen schönen Blumenstrauß.',
    'Die Bibliothek hat eine große Auswahl an Büchern.',
    'Mein Auto verbraucht zu viel Benzin.',
    'Wir grillen heute Abend im Garten.',
    'Das Hotel hat einen wunderschönen Pool.',
    'Sie schreibt täglich in ihr Tagebuch.',
    'Der Bäcker öffnet schon um fünf Uhr morgens.',
    'Ich lerne fleißig für die nächste Prüfung.',
    'Die Kinder bauen einen Schneemann im Garten.',
    'Mein Großvater feiert seinen achtzigsten Geburtstag.',
    'Wir machen heute einen Filmabend zu Hause.',
    'Das Eis im Sommer ist immer eine Erfrischung.',
    'Sie repariert gerade ihr altes Fahrrad.',
    'Der Bahnhof wird komplett umgebaut.',
    'Ich habe heute zwei wichtige Termine.',
    'Die Sterne sind heute Nacht besonders klar zu sehen.',
    'Mein Hund hat seinen Lieblingsknochen verloren.',
    'Wir feiern Silvester bei guten Freunden.',
    'Das Geschenk hat meiner Mutter sehr gefallen.',
    'Sie spricht fließend drei verschiedene Sprachen.',
    'Der Urlaub am Meer war wirklich erholsam.',
    'Ich brauche einen starken Kaffee am Morgen.',
    'Die Katze springt gerne auf das Bücherregal.',
    'Mein Vater hat einen grünen Daumen im Garten.',
    'Wir laufen jeden Sonntag eine große Runde.',
    'Das Restaurant ist heute leider geschlossen.',
    'Sie macht eine Ausbildung zur Krankenschwester.',
    'Der Künstler stellt seine Werke im Museum aus.',
    'Ich höre dem Vortrag aufmerksam zu.',
    'Die Sonne geht heute besonders schön unter.',
    'Mein Bruder spielt in einer Rockband Schlagzeug.',
    'Wir haben einen wunderschönen Sonnenuntergang gesehen.',
    'Das Wasser im Schwimmbad ist angenehm warm.',
    'Sie macht jedes Jahr Urlaub in Italien.',
    'Der Lehrer ist sehr geduldig mit den Schülern.',
    'Ich gehe heute Abend früh ins Bett.',
    'Die neue Wohnung ist deutlich größer als die alte.',
    'Mein Onkel sammelt alte Münzen aus aller Welt.',
    'Wir lernen jeden Tag etwas Neues dazu.',
    'Das Buch wurde in viele Sprachen übersetzt.',
    'Sie pflegt die Pflanzen mit großer Hingabe.',
    'Der Park ist im Frühling besonders schön.',
    'Ich brauche dringend ein paar Tage Urlaub.',
    'Die Kinder schauen begeistert den Zauberer an.',
    'Mein Auto springt bei der Kälte schlecht an.',
    'Wir backen am Wochenende einen leckeren Apfelkuchen.',
    'Das alte Klavier braucht dringend eine Stimmung.',
    'Sie geht regelmäßig zum Schwimmen ins Hallenbad.',
    'Der Kellner war sehr freundlich und aufmerksam.',
    'Ich vergesse nie meinen ersten Tag in der Schule.',
    'Die Nachbarn machen wieder eine laute Party.',
    'Mein Großvater hat im Krieg gekämpft.',
    'Wir sammeln Pilze im nahegelegenen Wald.',
    'Das Spiel war sehr spannend bis zum Ende.',
    'Sie hat eine Sammlung alter Schallplatten.',
    'Der Bahnhof ist heute Morgen sehr voll.',
    'Ich kaufe meine Lebensmittel auf dem Wochenmarkt.',
    'Die Brücke verbindet die beiden Stadtteile.',
    'Mein Freund hat einen neuen Hund adoptiert.',
    'Wir fliegen im Sommer nach Griechenland.',
    'Das Picknick im Park war sehr gemütlich.',
    'Sie hat eine neue Stelle als Lehrerin angenommen.',
    'Der Fernseher ist seit gestern kaputt.',
    'Ich treffe meine Freunde im Café in der Innenstadt.',
    'Die Bergwanderung war ziemlich anstrengend aber schön.',
    'Mein Kollege hat eine geniale Idee gehabt.',
    'Wir sehen uns morgen Abend bei dir zu Hause.',
    'Das Gemälde im Wohnzimmer ist sehr wertvoll.',
    'Sie liebt es, früh am Morgen aufzustehen.',
    'Der See ist im Sommer ein beliebter Treffpunkt.',
    'Ich kaufe ein neues Kleid für die Hochzeit.',
    'Die Universitätsbibliothek hat sehr lange Öffnungszeiten.',
    'Mein Hund bellt jeden Tag den Postboten an.',
    'Wir gehen abends gerne in die Oper.',
    'Das Wetter heute ist perfekt für einen Ausflug.',
    'Sie hat eine neue Brille mit goldenem Rahmen.',
    'Der Strand war heute morgen menschenleer.',
    'Ich vermisse meine Familie sehr während der Reise.',
    'Die Katze versteckt sich gerne unter dem Bett.',
    'Mein Bruder ist letzte Woche umgezogen.',
    'Wir lernen für unseren Schwimmschein.',
    'Das Frühstück im Hotel war wirklich reichhaltig.',
    'Sie joggt jeden Morgen entlang des Flusses.',
    'Der Friseur hat mir eine schöne neue Frisur gemacht.',
    'Ich habe gestern einen Marathon gelaufen.',
    'Die Bäume im Park sind über hundert Jahre alt.',
    'Mein Vater kocht das beste Gulasch der Welt.',
    'Wir besuchen am Wochenende eine Kunstausstellung.',
    'Das neue Auto fährt sich wunderbar leise.',
    'Sie trinkt jeden Morgen einen frischen Orangensaft.',
    'Der Computer braucht ein neues Betriebssystem.',
    'Ich vergesse nie unsere erste Begegnung.',
    'Die Schauspielerin hat einen wichtigen Preis gewonnen.',
    'Mein Auto braucht dringend einen Ölwechsel.',
    'Wir genießen die ruhigen Tage am Meer.',
    'Das Kind ist heute zum ersten Mal alleine in den Kindergarten gegangen.',
    'Sie spielt sehr leidenschaftlich Schach im Verein.',
    'Der Dachboden ist voller alter Erinnerungen.',
    'Ich lese die Zeitung jeden Morgen beim Frühstück.',
    'Die Fußgängerzone ist samstags immer sehr belebt.',
    'Mein Onkel züchtet Bienen in seinem Garten.',
    'Wir haben einen neuen Tisch für das Esszimmer gekauft.',
    'Das Konzert im Stadtpark war ausverkauft.',
    'Sie schreibt Gedichte für die Schulzeitung.',
    'Der Kuchen ist mir leider verbrannt.',
    'Ich wünsche dir einen wunderschönen Tag.',
    'Die alten Fotos erinnern mich an meine Kindheit.',
    'Mein Bruder hat eine neue Freundin kennengelernt.',
    'Wir feiern Weihnachten immer bei meinen Eltern.',
    'Das Buchgeschäft hat eine gemütliche Leseecke.',
    'Sie macht heute Abend einen veganen Auflauf.',
    'Der Schreiner baut uns einen neuen Schrank.',
    'Ich freue mich auf das gemeinsame Abendessen.',
    'Die Vögel zwitschern bereits am frühen Morgen.',
    'Mein Großvater hat mir das Schachspielen beigebracht.',
    'Wir suchen ein neues Hotel für den Urlaub.',
    'Das Pferd auf der Weide gehört unserem Nachbarn.',
    'Sie hat einen wunderschönen Ring zum Geburtstag bekommen.',
    'Der Tisch ist für vier Personen gedeckt.',
    'Ich brauche neue Vorhänge für das Schlafzimmer.',
    'Die Schule organisiert einen großen Ausflug.',
    'Mein Hund liebt es, im Schnee zu spielen.',
    'Wir trinken Tee mit frischer Minze aus dem Garten.',
    'Das Gewitter kam ganz plötzlich am Nachmittag.',
    'Sie übt fleißig für ihr Klavierkonzert.',
    'Der Bürgermeister hält morgen eine wichtige Rede.',
    'Ich putze mir jeden Abend gründlich die Zähne.',
    'Die Kinder lernen das Alphabet sehr schnell.',
    'Mein Auto hat einen platten Reifen vorne links.',
    'Wir sammeln Kastanien für den Herbstkranz.',
    'Das Restaurant ist berühmt für seine Pizza.',
    'Sie näht ein wunderschönes Brautkleid für ihre Tochter.',
    'Der Vortrag des Professors war sehr informativ.',
    'Ich stehe jeden Morgen um sechs Uhr auf.',
    'Die alte Eiche im Garten ist majestätisch.',
    'Mein Onkel arbeitet als Tierarzt auf dem Land.',
    'Wir fahren heute gemeinsam zum Einkaufszentrum.',
    'Das Schwimmbad ist im Sommer immer überfüllt.',
    'Sie liest dem Kind jeden Abend eine Geschichte vor.',
    'Der Garten muss dringend gegossen werden.',
];